[package]
name = "cooklang-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
cooklang = "0.13.3"
wasm-bindgen = "0.2"
serde_json = "1"
serde-wasm-bindgen = "0.6"

[lib]
crate-type = ["cdylib", "rlib"]
